---
- name: Parse Raw Login Commands
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    send_email_report: true
    token_regex: "(sha256~[a-zA-Z0-9._-]+)"
    url_regex: "(https://[a-zA-Z0-9.-]+:[0-9]+)"
    # Regex to grab the cluster's base domain for naming
    name_regex: "https://api.([a-zA-Z0-9.-]+):"

  tasks:
    - name: Parse raw input and create dynamic inventory
      ansible.builtin.add_host:
        # Use the cluster FQDN as the name. Default to a timestamp if parsing fails.
        name: "{{ item | regex_search(name_regex, '\\1') | first | default('cluster-' + ansible_date_time.epoch) }}"
        groups: "dynamic_clusters"
        api_token: "{{ item | regex_search(token_regex) }}"
        api_url: "{{ item | regex_search(url_regex) }}"
        email_recipient: "{{ email_recipient | default('admin@example.com') }}"
      loop: "{{ raw_login_list.split('\n') }}"
      when: 
        - item | length > 10
        - item | regex_search(token_regex)
        - item | regex_search(url_regex)

- name: OpenShift Cluster Audit & Reporting
  hosts: dynamic_clusters
  connection: local
  gather_facts: false
  strategy: free

  tasks:
    - name: Create temporary workspace
      ansible.builtin.tempfile:
        state: directory
        suffix: "_{{ inventory_hostname }}"
      register: temp_dir

    - name: Run Full Audit Script
      block:
        - name: "Execute and Stream Output"
          ansible.builtin.shell:
            cmd: |
              set -e
              export KUBECONFIG="./kubeconfig"
              
              echo "--- LOGGING INTO: {{ api_url }} ---"
              if ! oc login {{ api_url }} --token={{ api_token }} --insecure-skip-tls-verify=true > /dev/null 2>&1; then
                echo "CRITICAL: Login Failed for {{ api_url }}"
                exit 1
              fi

              # Original script logic with 'tee' for stdout visibility
              echo "--- CLUSTER ID ---" | tee clusterID.txt
              oc get clusterversion version -o custom-columns=ID:.spec.clusterID --no-headers | tee -a clusterID.txt
              
              echo -e "\n--- CLUSTER OPERATORS ---"
              oc get clusteroperators | tee operators.txt
              
              echo -e "\n--- CLUSTER SERVICE VERSIONS ---"
              oc get csv | tee -a operators.txt
              
              echo -e "\n--- NODES LIST ---"
              oc get nodes | tee get_nodes.txt
              
              cut -f 1 -d ' ' get_nodes.txt | grep '[a-z]' > node_list.tmp
              while read node; do 
                echo -e "\n--- DESCRIBE NODE: $node ---"
                oc describe node "$node" | tee -a node_cpu.txt 
              done < node_list.tmp
              
              tar -czvf ocp_cluster_reporting.tar *.txt > /dev/null
              echo -e "\n--- AUDIT FINISHED: {{ api_url }} ---"
            chdir: "{{ temp_dir.path }}"
          register: audit_output

        - name: "STDOUT VIEW"
          ansible.builtin.debug:
            var: audit_output.stdout_lines

        - name: Email full report
          community.general.mail:
            host: smtp.example.com
            port: 25
            subject: "OpenShift Audit Report: {{ inventory_hostname }}"
            from: "ansible-reports@example.com"
            to: "{{ email_recipient }}"
            body: "Audit complete for {{ inventory_hostname }} ({{ api_url }})."
            attach:
              - "{{ temp_dir.path }}/ocp_cluster_reporting.tar"
          when: hostvars['localhost']['send_email_report'] | bool
          ignore_errors: true

        - name: Record Success
          ansible.builtin.set_fact:
            audit_status: "SUCCESS"
          
      rescue:
        - name: Record Failure
          ansible.builtin.set_fact:
            audit_status: "FAILED"

      always:
        - name: Cleanup workspace
          ansible.builtin.file:
            path: "{{ temp_dir.path }}"
            state: absent
          when: temp_dir.path is defined

- name: Final Audit Summary
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Generate Summary Table
      ansible.builtin.debug:
        msg: |
          +--------------------------------------------------------------------------------------------------+
          | AUDIT SUMMARY REPORT                                                                             |
          +--------------------------------------------------------------------------------------------------+
          | CLUSTER DOMAIN                 | STATUS     | API URL                                            |
          +--------------------------------------------------------------------------------------------------+
          {% for host in groups['dynamic_clusters'] %}
          | {{ host.ljust(30) }} | {{ (hostvars[host]['audit_status'] | default('SKIPPED')).ljust(10) }} | {{ (hostvars[host]['api_url'] | default('N/A')).ljust(45) }} |
          {% endfor %}
          +--------------------------------------------------------------------------------------------------+
