---
- name: Parse Raw Login Commands
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    send_email_report: true
    token_regex: "(sha256~[a-zA-Z0-9._-]+)"
    url_regex: "(https://[a-zA-Z0-9.-]+:[0-9]+)"

  tasks:
    - name: Parse raw input and create dynamic inventory
      ansible.builtin.add_host:
        name: "cluster_{{ item_index }}"
        groups: "dynamic_clusters"
        api_token: "{{ item | regex_search(token_regex) }}"
        api_url: "{{ item | regex_search(url_regex) }}"
        email_recipient: "{{ email_recipient | default('admin@example.com') }}"
      loop: "{{ raw_login_list.split('\n') }}"
      loop_control:
        index_var: item_index
      when: 
        - item | length > 10
        - item | regex_search(token_regex)
        - item | regex_search(url_regex)

- name: OpenShift Cluster Audit & Reporting
  hosts: dynamic_clusters
  connection: local
  gather_facts: false
  strategy: free

  tasks:
    - name: Create temporary workspace
      ansible.builtin.tempfile:
        state: directory
        suffix: "_{{ inventory_hostname }}"
      register: temp_dir

    - name: Run Full Audit Script
      block:
        - name: "Execute and Stream Output for {{ api_url }}"
          ansible.builtin.shell:
            cmd: |
              set -e
              export KUBECONFIG="./kubeconfig"
              
              echo "--- ATTEMPTING LOGIN: {{ api_url }} ---"
              if ! oc login {{ api_url }} --token={{ api_token }} --insecure-skip-tls-verify=true > /dev/null 2>&1; then
                echo "CRITICAL ERROR: Login Failed for {{ api_url }}"
                exit 1
              fi

              # --- CLUSTER ID ---
              echo "--- CLUSTER ID ---" | tee clusterID.txt
              oc get clusterversion version -o custom-columns=ID:.spec.clusterID --no-headers | tee -a clusterID.txt
              
              # --- OPERATORS & CSVs ---
              echo -e "\n--- CLUSTER OPERATORS ---"
              oc get clusteroperators | tee operators.txt
              echo -e "\n--- CLUSTER SERVICE VERSIONS ---"
              oc get csv | tee -a operators.txt
              
              # --- NODES ---
              echo -e "\n--- NODES LIST ---"
              oc get nodes | tee get_nodes.txt
              
              # --- NODE DESCRIPTIONS ---
              # We use 'cut' as in your original script to loop
              cut -f 1 -d ' ' get_nodes.txt | grep '[a-z]' > node_list.tmp
              while read node; do 
                echo -e "\n--- DESCRIBE NODE: $node ---"
                oc describe node "$node" | tee -a node_cpu.txt 
              done < node_list.tmp
              
              # --- HASHES ---
              echo -e "\n--- FILE HASHES ---" | tee hash.txt
              md5sum get_nodes.txt node_cpu.txt clusterID.txt operators.txt | tee -a hash.txt
              
              # --- ARCHIVE ---
              tar -czvf ocp_cluster_reporting.tar get_nodes.txt node_cpu.txt hash.txt clusterID.txt operators.txt > /dev/null
              echo -e "\n--- AUDIT FINISHED: {{ api_url }} ---"
            chdir: "{{ temp_dir.path }}"
          register: audit_output

        # This task prints the entire capture of the script to the AAP UI
        - name: "STDOUT LOGS: {{ api_url }}"
          ansible.builtin.debug:
            var: audit_output.stdout_lines

        - name: Email full report archive
          community.general.mail:
            host: smtp.example.com
            port: 25
            subject: "Full OpenShift Audit: {{ api_url }}"
            from: "ansible-reports@example.com"
            to: "{{ email_recipient }}"
            body: "Audit complete for {{ api_url }}. See attached tarball for details."
            attach:
              - "{{ temp_dir.path }}/ocp_cluster_reporting.tar"
          when: hostvars['localhost']['send_email_report'] | bool
          ignore_errors: true

      always:
        - name: Cleanup workspace
          ansible.builtin.file:
            path: "{{ temp_dir.path }}"
            state: absent
          when: temp_dir.path is defined
