---
- name: Parse Raw Login Commands
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    send_email_report: true
    show_stdout_report: true
    token_regex: "(sha256~[a-zA-Z0-9._-]+)"
    url_regex: "(https://[a-zA-Z0-9.-]+:[0-9]+)"

  tasks:
    - name: Parse raw input and create dynamic inventory
      ansible.builtin.add_host:
        name: "cluster_{{ item_index }}"
        groups: "dynamic_clusters"
        api_token: "{{ item | regex_search(token_regex) }}"
        api_url: "{{ item | regex_search(url_regex) }}"
        email_recipient: "{{ email_recipient | default('admin@example.com') }}"
      loop: "{{ raw_login_list.split('\n') }}"
      loop_control:
        index_var: item_index
      when: 
        - item | length > 10
        - item | regex_search(token_regex)
        - item | regex_search(url_regex)

- name: OpenShift Cluster Audit & Reporting
  hosts: dynamic_clusters
  connection: local
  gather_facts: false

  tasks:
    - name: Create temporary workspace
      ansible.builtin.tempfile:
        state: directory
        suffix: "_{{ inventory_hostname }}"
      register: temp_dir

    - name: Run Full Audit Script
      block:
        - name: Execute your original shell logic
          ansible.builtin.shell:
            cmd: |
              set -e
              export KUBECONFIG="./kubeconfig"
              
              # 1. Login
              if ! oc login {{ api_url }} --token={{ api_token }} --insecure-skip-tls-verify=true > /dev/null 2>&1; then
                echo "CRITICAL: Login Failed for {{ api_url }}" > cluster_summary.log
                exit 0
              fi

              # 2. RUN YOUR EXACT SCRIPT LOGIC
              echo "Gathering data for {{ api_url }}..."
              
              # Using custom-columns to avoid the JSONPath \n error
              oc get clusterversion version -o custom-columns=ID:.spec.clusterID --no-headers > clusterID.txt
              oc get clusteroperators > operators.txt
              oc get csv >> operators.txt
              
              # Get Nodes
              oc get nodes | cut -f 1 -d ' ' | grep '[a-z]' >> get_nodes.txt
              
              # Describe Nodes Loop
              while read node; do 
                oc describe node "$node" >> node_cpu.txt 
              done < get_nodes.txt
              
              # Generate Hashes
              md5sum get_nodes.txt >> hash.txt 
              md5sum node_cpu.txt >> hash.txt 
              md5sum clusterID.txt >> hash.txt 
              md5sum operators.txt >> hash.txt
              
              # Create a consolidated summary for Stdout (Optional, but helpful)
              echo "--- CLUSTER ID ---" > cluster_summary.log
              cat clusterID.txt >> cluster_summary.log
              echo -e "\n--- NODE COUNT ---" >> cluster_summary.log
              wc -l < get_nodes.txt >> cluster_summary.log
              echo -e "\n--- RECENT OPERATOR ISSUES ---" >> cluster_summary.log
              grep -v "False.*False.*False" operators.txt | grep -v "AVAILABLE" | head -n 20 >> cluster_summary.log || echo "All Operators Healthy" >> cluster_summary.log

              # Tar everything as requested
              tar -czvf ocp_cluster_reporting.tar get_nodes.txt node_cpu.txt hash.txt clusterID.txt operators.txt cluster_summary.log > /dev/null
            chdir: "{{ temp_dir.path }}"

        # --- VIEW SUMMARY IN AAP STDOUT ---
        - name: "AUDIT SUMMARY: {{ api_url }}"
          ansible.builtin.debug:
            msg: "{{ lookup('file', temp_dir.path + '/cluster_summary.log').split('\n') }}"
          when: hostvars['localhost']['show_stdout_report'] | bool
          ignore_errors: true

        # --- EMAIL THE FULL TARBALL ---
        - name: Email full report archive
          community.general.mail:
            host: smtp.example.com
            port: 25
            subject: "Full OpenShift Audit: {{ api_url }}"
            from: "ansible-reports@example.com"
            to: "{{ email_recipient }}"
            body: "Audit complete. The attached tarball contains cluster ID, full operator list, CSVs, and all node descriptions."
            attach:
              - "{{ temp_dir.path }}/ocp_cluster_reporting.tar"
          when: hostvars['localhost']['send_email_report'] | bool
          ignore_errors: true

      always:
        - name: Cleanup workspace
          ansible.builtin.file:
            path: "{{ temp_dir.path }}"
            state: absent
          when: temp_dir.path is defined
