---
- name: Parse Raw Login Commands
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    send_email_report: true
    show_stdout_report: true
    token_regex: "(sha256~[a-zA-Z0-9._-]+)"
    url_regex: "(https://[a-zA-Z0-9.-]+:[0-9]+)"

  tasks:
    - name: Parse raw input and create dynamic inventory
      ansible.builtin.add_host:
        name: "cluster_{{ item_index }}"
        groups: "dynamic_clusters"
        api_token: "{{ item | regex_search(token_regex) }}"
        api_url: "{{ item | regex_search(url_regex) }}"
        email_recipient: "{{ email_recipient | default('admin@example.com') }}"
      loop: "{{ raw_login_list.split('\n') }}"
      loop_control:
        index_var: item_index
      when: 
        - item | length > 10
        - item | regex_search(token_regex)
        - item | regex_search(url_regex)

- name: OpenShift Cluster Audit & Reporting
  hosts: dynamic_clusters
  connection: local
  gather_facts: false

  tasks:
    - name: Create temporary workspace
      ansible.builtin.tempfile:
        state: directory
        suffix: "_{{ inventory_hostname }}"
      register: temp_dir

    - name: Run Audit Script
      block:
        - name: Execute audit and generate files
          ansible.builtin.shell:
            cmd: |
              set -e
              export KUBECONFIG="./kubeconfig"
              
              # Try to login, if it fails, log it to summary and exit 0 to allow reporting
              if ! oc login {{ api_url }} --token={{ api_token }} --insecure-skip-tls-verify=true > /dev/null 2>&1; then
                echo "CRITICAL: Login Failed for {{ api_url }}" > summary.log
                exit 0
              fi
              
              # Gather data
              oc get clusterversion version -o custom-columns=ID:.spec.clusterID --no-headers > clusterID.txt
              oc get clusteroperators > operators.txt
              
              # Summary logic
              echo "--- CLUSTER ID ---" > summary.log
              cat clusterID.txt >> summary.log
              echo -e "\n--- DEGRADED OPERATORS ---" >> summary.log
              # Use grep safely (|| true prevents the script from failing if no degraded operators are found)
              grep -v "False.*False.*False" operators.txt | grep -v "AVAILABLE" >> summary.log || echo "All Operators Healthy" >> summary.log
              
              # Archive
              tar -czvf ocp_cluster_reporting.tar *.txt summary.log > /dev/null
            chdir: "{{ temp_dir.path }}"
          register: shell_output

        # 1. FIXED: We use the registered output from the shell task 
        # instead of trying to 'cat' the file again with a new task.
        - name: "REPORT FOR: {{ api_url }}"
          ansible.builtin.debug:
            msg: "{{ lookup('file', temp_dir.path + '/summary.log').split('\n') }}"
          when: 
            - hostvars['localhost']['show_stdout_report'] | bool
            - temp_dir.path is defined
          ignore_errors: true

        - name: Email the results
          community.general.mail:
            host: smtp.example.com
            port: 25
            subject: "OpenShift Audit Report: {{ api_url }}"
            from: "ansible-reports@example.com"
            to: "{{ email_recipient }}"
            body: "Attached is the audit report for {{ api_url }}"
            attach:
              - "{{ temp_dir.path }}/ocp_cluster_reporting.tar"
          when: 
            - hostvars['localhost']['send_email_report'] | bool
            - temp_dir.path + '/ocp_cluster_reporting.tar' is exists
          ignore_errors: true
      
      always:
        - name: Cleanup workspace
          ansible.builtin.file:
            path: "{{ temp_dir.path }}"
            state: absent
          when: temp_dir.path is defined
